package co.edu.uniandes.cloud.domain;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.fasterxml.jackson.annotation.JsonIgnore;

import javax.persistence.*;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;
import java.io.Serializable;
import java.math.BigDecimal;
import java.time.Instant;
import java.time.LocalDate;
import java.util.HashSet;
import java.util.Objects;
import java.util.Set;

/**
 * A Contest.
 */
@Entity
@Table(name = "contest")
public class Contest implements Serializable {

    private static final long serialVersionUID = 1L;
    public static final String TABLE_NAME = "contest";

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    private String id;

    @Column(name = "create_date", nullable = false)
    @DynamoDBAttribute
    private Instant createDate;

    @NotNull
    @Column(name = "name", nullable = false)
    @DynamoDBAttribute
    private String name;

    @Lob
    @Column(name = "logo")
    private byte[] logo;

    @Column(name = "logo_content_type")
    @DynamoDBAttribute
    private String logoContentType;

    @NotNull
    @Column(name = "uuid", nullable = false, unique = true)
    @DynamoDBAttribute
    private String uuid;

    @NotNull
    @Column(name = "start_date", nullable = false)
    @DynamoDBAttribute
    private LocalDate startDate;

    @NotNull
    @Column(name = "end_date", nullable = false)
    @DynamoDBAttribute
    private LocalDate endDate;

    @NotNull
    @Column(name = "price", precision=10, scale=2, nullable = false)
    @DynamoDBAttribute
    private BigDecimal price;

    @NotNull
    @Lob
    @Column(name = "script", nullable = false)
    @DynamoDBAttribute
    private String script;

    @Size(max = 1024)
    @Column(name = "notes", length = 1024)
    @DynamoDBAttribute
    private String notes;

    @OneToMany(mappedBy = "contest")
    @JsonIgnore
    private Set<Application> applications = new HashSet<>();

    @ManyToOne(optional = false)
    private User user;

    // jhipster-needle-entity-add-field - JHipster will add fields here, do not remove
    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public Instant getCreateDate() {
        return createDate;
    }

    public Contest createDate(Instant createDate) {
        this.createDate = createDate;
        return this;
    }

    public void setCreateDate(Instant createDate) {
        this.createDate = createDate;
    }

    public String getName() {
        return name;
    }

    public Contest name(String name) {
        this.name = name;
        return this;
    }

    public void setName(String name) {
        this.name = name;
    }

    public byte[] getLogo() {
        return logo;
    }

    public Contest logo(byte[] logo) {
        this.logo = logo;
        return this;
    }

    public void setLogo(byte[] logo) {
        this.logo = logo;
    }

    public String getLogoContentType() {
        return logoContentType;
    }

    public Contest logoContentType(String logoContentType) {
        this.logoContentType = logoContentType;
        return this;
    }

    public void setLogoContentType(String logoContentType) {
        this.logoContentType = logoContentType;
    }

    public String getUuid() {
        return uuid;
    }

    public Contest uuid(String uuid) {
        this.uuid = uuid;
        return this;
    }

    public void setUuid(String uuid) {
        this.uuid = uuid;
    }

    public LocalDate getStartDate() {
        return startDate;
    }

    public Contest startDate(LocalDate startDate) {
        this.startDate = startDate;
        return this;
    }

    public void setStartDate(LocalDate startDate) {
        this.startDate = startDate;
    }

    public LocalDate getEndDate() {
        return endDate;
    }

    public Contest endDate(LocalDate endDate) {
        this.endDate = endDate;
        return this;
    }

    public void setEndDate(LocalDate endDate) {
        this.endDate = endDate;
    }

    public BigDecimal getPrice() {
        return price;
    }

    public Contest price(BigDecimal price) {
        this.price = price;
        return this;
    }

    public void setPrice(BigDecimal price) {
        this.price = price;
    }

    public String getScript() {
        return script;
    }

    public Contest script(String script) {
        this.script = script;
        return this;
    }

    public void setScript(String script) {
        this.script = script;
    }

    public String getNotes() {
        return notes;
    }

    public Contest notes(String notes) {
        this.notes = notes;
        return this;
    }

    public void setNotes(String notes) {
        this.notes = notes;
    }

    public Set<Application> getApplications() {
        return applications;
    }

    public Contest applications(Set<Application> applications) {
        this.applications = applications;
        return this;
    }

    public Contest addApplication(Application application) {
        this.applications.add(application);
        application.setContest(this);
        return this;
    }

    public Contest removeApplication(Application application) {
        this.applications.remove(application);
        application.setContest(null);
        return this;
    }

    public void setApplications(Set<Application> applications) {
        this.applications = applications;
    }

    public User getUser() {
        return user;
    }

    public Contest user(User user) {
        this.user = user;
        return this;
    }

    public void setUser(User user) {
        this.user = user;
    }
    // jhipster-needle-entity-add-getters-setters - JHipster will add getters and setters here, do not remove

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        Contest contest = (Contest) o;
        if (contest.getId() == null || getId() == null) {
            return false;
        }
        return Objects.equals(getId(), contest.getId());
    }

    @Override
    public int hashCode() {
        return Objects.hashCode(getId());
    }

    @Override
    public String toString() {
        return "Contest{" +
            "id=" + getId() +
            ", createDate='" + getCreateDate() + "'" +
            ", name='" + getName() + "'" +
            ", logo='" + getLogo() + "'" +
            ", logoContentType='" + getLogoContentType() + "'" +
            ", uuid='" + getUuid() + "'" +
            ", startDate='" + getStartDate() + "'" +
            ", endDate='" + getEndDate() + "'" +
            ", price=" + getPrice() +
            ", script='" + getScript() + "'" +
            ", notes='" + getNotes() + "'" +
            "}";
    }
}
