package com.baeldung.spring.data.dynamodb.model;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import lombok.ToString;

import java.time.Instant;

@DynamoDBTable(tableName = "ProductInfo")
@ToString
public class ProductInfo {
    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    private String id;

    @DynamoDBAttribute
    private String msrp;

    @DynamoDBAttribute
    private String cost;

    @DynamoDBTypeConverted( converter = InstantConverter_DyDB.class )
    private Instant createDate;

    public ProductInfo() {
    }

    public ProductInfo(String cost, String msrp) {
        this.msrp = msrp;
        this.cost = cost;
    }


    public String getId() {
        return id;
    }

    public String getMsrp() {
        return msrp;
    }

    public String getCost() {
        return cost;
    }

    public void setId(String id) {
        this.id = id;
    }

    public void setMsrp(String msrp) {
        this.msrp = msrp;
    }

    public void setCost(String cost) {
        this.cost = cost;
    }

    public Instant getCreateDate() {
        return createDate;
    }

    public void setCreateDate(Instant createDate) {
        this.createDate = createDate;
    }

    static public class InstantConverter_DyDB implements DynamoDBTypeConverter<String, Instant> {
        @Override
        public String convert(Instant object) {
            return object.toString();
        }

        @Override
        public Instant unconvert(String string) {
            return Instant.parse(string);
        }
    }
}
